-- ============================================================================
-- Hootsuite Streamlit App Generator Procedure
-- ============================================================================
-- Purpose: Generate, deploy, and return link to Streamlit app in Snowflake
-- Uses PUT with base64 encoding to write app file to stage
-- ============================================================================

USE DATABASE HOOTSUITE_INTELLIGENCE;
USE SCHEMA ANALYTICS;
USE WAREHOUSE HOOTSUITE_WH;

-- ============================================================================
-- Streamlit App Generator Procedure
-- ============================================================================
CREATE OR REPLACE PROCEDURE GENERATE_STREAMLIT_FROM_CHART(
    CHART_SQL TEXT,
    CHART_TITLE TEXT,
    ANALYSIS_TYPE TEXT
)
RETURNS TEXT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.10'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'main'
AS $$
import base64

def main(session, CHART_SQL, CHART_TITLE, ANALYSIS_TYPE):
    """
    Generate and deploy a Streamlit app with clickable link
    """
    
    # Clean app name
    app_name = f"analysis_app_{CHART_TITLE.lower().replace(' ', '_').replace('-', '_')}"
    app_name = ''.join(c if c.isalnum() or c == '_' else '_' for c in app_name)
    app_name = app_name[:50]  # Snowflake name limit
    
    # Escape SQL for Python string
    chart_sql_escaped = CHART_SQL.replace('\\', '\\\\').replace("'", "\\'")
    
    # Generate Streamlit app code
    streamlit_code = f"""import streamlit as st
import pandas as pd
import plotly.express as px
from snowflake.snowpark.context import get_active_session

st.set_page_config(page_title="{CHART_TITLE}", layout="wide")
session = get_active_session()

st.title("📊 {CHART_TITLE}")
st.markdown("---")

@st.cache_data
def load_data():
    query = '''{chart_sql_escaped}'''
    return session.sql(query).to_pandas()

try:
    df = load_data()
    if df.empty:
        st.warning("No data returned")
        st.stop()
except Exception as e:
    st.error(f"Error: {{e}}")
    st.stop()

st.subheader("📋 Data Table")
st.dataframe(df, use_container_width=True, height=400)
st.caption(f"Total Records: {{len(df):,}}")

numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

if numeric_cols and categorical_cols:
    st.subheader("📈 Visualizations")
    col1, col2 = st.columns(2)
    
    with col1:
        fig = px.bar(df, x=categorical_cols[0], y=numeric_cols[0], 
                    title=f"{{numeric_cols[0]}} by {{categorical_cols[0]}}")
        st.plotly_chart(fig, use_container_width=True)
    
    with col2:
        if len(numeric_cols) >= 2:
            fig = px.scatter(df, x=numeric_cols[0], y=numeric_cols[1],
                           title="Scatter Plot")
            st.plotly_chart(fig, use_container_width=True)
        else:
            fig = px.histogram(df, x=numeric_cols[0], title="Distribution")
            st.plotly_chart(fig, use_container_width=True)

if numeric_cols and "{ANALYSIS_TYPE}" == "statistical":
    st.subheader("📊 Statistical Analysis")
    col1, col2 = st.columns(2)
    
    with col1:
        st.write("**Descriptive Statistics**")
        st.dataframe(df[numeric_cols].describe())
    
    with col2:
        if len(numeric_cols) > 1:
            st.write("**Correlations**")
            corr = df[numeric_cols].corr()
            fig = px.imshow(corr, text_auto=True, color_continuous_scale="RdBu_r")
            st.plotly_chart(fig, use_container_width=True)

if numeric_cols:
    st.subheader("🎯 Key Metrics")
    cols = st.columns(min(4, len(numeric_cols)))
    for idx, col in enumerate(numeric_cols[:4]):
        with cols[idx]:
            st.metric(col, f"{{df[col].sum():,.0f}}", 
                     delta=f"Avg: {{df[col].mean():,.2f}}")

st.subheader("💾 Export")
col1, col2 = st.columns(2)
with col1:
    csv = df.to_csv(index=False)
    st.download_button("📥 Download CSV", csv, "data.csv", use_container_width=True)
with col2:
    json_data = df.to_json(orient="records", indent=2)
    st.download_button("📥 Download JSON", json_data, "data.json", use_container_width=True)

st.markdown("---")
st.caption("🤖 Generated by Hootsuite Intelligence Agent | Powered by Snowflake")
"""
    
    try:
        # Encode the Streamlit code to base64
        encoded_code = base64.b64encode(streamlit_code.encode()).decode()
        
        # Put the code in a stage using base64 data URI
        session.sql(f"""
            PUT 'data:text/plain;base64,{encoded_code}' 
            @~/streamlit_apps/{app_name}.py
        """).collect()
        
        # Create the Streamlit app
        create_streamlit_sql = f"""
            CREATE OR REPLACE STREAMLIT HOOTSUITE_INTELLIGENCE.ANALYTICS.{app_name}
            ROOT_LOCATION = '@~/streamlit_apps/'
            MAIN_FILE = '{app_name}.py'
            QUERY_WAREHOUSE = 'HOOTSUITE_WH'
            TITLE = '{CHART_TITLE} - Interactive Analysis'
        """
        
        session.sql(create_streamlit_sql).collect()
        
        # Get account info for URL
        account_info = session.sql("SELECT CURRENT_ACCOUNT() as acct, CURRENT_REGION() as reg").collect()[0]
        account = account_info['ACCT']
        region = account_info['REG']
        
        # Build Snowsight URL
        url = f"https://app.snowflake.com/{region}/{account}/#/streamlit-apps/HOOTSUITE_INTELLIGENCE.ANALYTICS.{app_name}"
        
        return f"""✅ STREAMLIT APP DEPLOYED SUCCESSFULLY!

**🎉 Your app is live!**

**App Name:** {app_name}
**Location:** HOOTSUITE_INTELLIGENCE.ANALYTICS

🔗 **CLICK HERE TO LAUNCH YOUR APP:**
{url}

**Or navigate in Snowsight:**
Projects → Streamlit → {app_name}

**Features Included:**
✓ Interactive data table
✓ Dynamic visualizations (bar, scatter, histogram)
{"✓ Statistical analysis with correlations" if ANALYSIS_TYPE == "statistical" else "✓ Exploratory data analysis"}
✓ Key metrics dashboard
✓ CSV & JSON export
✓ Live Snowflake data connection

**Your app is ready to use immediately!** Click the link above."""
        
    except Exception as e:
        return f"""⚠️ Error creating Streamlit app: {str(e)}

**Troubleshooting:**
1. Verify you have CREATE STREAMLIT privilege
2. Check warehouse HOOTSUITE_WH is running
3. Try manual deployment:
   - Go to Snowsight → Projects → Streamlit
   - Click "+ Streamlit App"
   - Name: {app_name}
   - Copy the generated code (available in logs)

**App code was generated but automatic deployment failed.**"""

$$;

-- ============================================================================
-- Grant Permissions
-- ============================================================================
GRANT USAGE ON PROCEDURE HOOTSUITE_INTELLIGENCE.ANALYTICS.GENERATE_STREAMLIT_FROM_CHART(TEXT, TEXT, TEXT) TO ROLE SYSADMIN;
GRANT USAGE ON PROCEDURE HOOTSUITE_INTELLIGENCE.ANALYTICS.GENERATE_STREAMLIT_FROM_CHART(TEXT, TEXT, TEXT) TO ROLE PUBLIC;
GRANT CREATE STREAMLIT ON SCHEMA HOOTSUITE_INTELLIGENCE.ANALYTICS TO ROLE SYSADMIN;
GRANT CREATE STREAMLIT ON SCHEMA HOOTSUITE_INTELLIGENCE.ANALYTICS TO ROLE PUBLIC;

-- ============================================================================
-- Test Procedure (Commented out)
-- ============================================================================
-- CALL GENERATE_STREAMLIT_FROM_CHART(
--     'SELECT platform, COUNT(*) as post_count FROM HOOTSUITE_INTELLIGENCE.RAW.SOCIAL_ACCOUNTS GROUP BY platform',
--     'Platform Analysis Dashboard',
--     'exploratory'
-- );

SELECT 'Streamlit App Generator Procedure created successfully' AS STATUS;

