-- ============================================================================
-- Hootsuite Streamlit App Generator Procedure
-- ============================================================================
-- Purpose: Automatically generate and deploy Streamlit apps in Snowflake
-- Returns: Direct link to launch the created app
-- ============================================================================

USE DATABASE HOOTSUITE_INTELLIGENCE;
USE SCHEMA ANALYTICS;
USE WAREHOUSE HOOTSUITE_WH;

-- ============================================================================
-- Streamlit App Generator Procedure
-- ============================================================================
CREATE OR REPLACE PROCEDURE GENERATE_STREAMLIT_FROM_CHART(
    CHART_SQL TEXT,
    CHART_TITLE TEXT,
    ANALYSIS_TYPE TEXT
)
RETURNS TEXT
LANGUAGE SQL
AS
$$
DECLARE
    app_name VARCHAR;
    streamlit_code VARCHAR;
    result VARCHAR;
BEGIN
    -- Clean app name for Snowflake object naming
    app_name := REGEXP_REPLACE(LOWER(:CHART_TITLE), '[^a-z0-9_]', '_');
    app_name := 'HOOTSUITE_' || SUBSTR(app_name, 1, 40);
    
    -- Generate Streamlit app code
    streamlit_code := 'import streamlit as st
import pandas as pd
import plotly.express as px
from snowflake.snowpark.context import get_active_session

st.set_page_config(page_title="' || :CHART_TITLE || '", layout="wide")
session = get_active_session()

st.title("📊 ' || :CHART_TITLE || '")
st.markdown("---")

@st.cache_data
def load_data():
    return session.sql("""' || REPLACE(:CHART_SQL, '"', '""') || '""").to_pandas()

df = load_data()

if df.empty:
    st.warning("No data returned")
    st.stop()

st.subheader("Data Table")
st.dataframe(df, use_container_width=True)
st.caption(f"Total Records: {len(df):,}")

numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

if numeric_cols and categorical_cols:
    st.subheader("Visualizations")
    col1, col2 = st.columns(2)
    
    with col1:
        fig_bar = px.bar(df, x=categorical_cols[0], y=numeric_cols[0])
        st.plotly_chart(fig_bar, use_container_width=True)
    
    with col2:
        if len(numeric_cols) > 1:
            fig_scatter = px.scatter(df, x=numeric_cols[0], y=numeric_cols[1])
            st.plotly_chart(fig_scatter, use_container_width=True)

if numeric_cols and "' || :ANALYSIS_TYPE || '" = "statistical":
    st.subheader("Statistical Analysis")
    st.write(df[numeric_cols].describe())
    
    if len(numeric_cols) > 1:
        corr = df[numeric_cols].corr()
        fig = px.imshow(corr, text_auto=True, color_continuous_scale="RdBu_r")
        st.plotly_chart(fig, use_container_width=True)

st.subheader("Export")
csv = df.to_csv(index=False)
st.download_button("Download CSV", csv, "data.csv", "text/csv")

st.caption("Generated by Hootsuite Intelligence Agent")
';

    -- Create the Streamlit app
    EXECUTE IMMEDIATE 'CREATE OR REPLACE STREAMLIT HOOTSUITE_INTELLIGENCE.ANALYTICS.' || app_name || '
    FROM (SELECT ''' || streamlit_code || ''' AS code)
    MAIN_FILE = ''streamlit_app.py''
    QUERY_WAREHOUSE = ''HOOTSUITE_WH''';
    
    -- Get account and region for URL
    LET account_name VARCHAR := (SELECT CURRENT_ACCOUNT());
    LET region_name VARCHAR := (SELECT CURRENT_REGION());
    
    -- Construct Snowsight URL
    result := '✅ Streamlit app deployed successfully!

**App:** ' || app_name || '
**Database:** HOOTSUITE_INTELLIGENCE.ANALYTICS

**🔗 CLICK TO OPEN YOUR APP:**
https://app.snowflake.com/' || region_name || '/' || account_name || '/#/streamlit-apps/HOOTSUITE_INTELLIGENCE.ANALYTICS.' || app_name || '

**Or navigate manually:**
Snowsight → Projects → Streamlit → ' || app_name || '

**Features:**
✓ Interactive data table
✓ Dynamic visualizations
' || (CASE WHEN :ANALYSIS_TYPE = 'statistical' THEN '✓ Statistical analysis with correlations' ELSE '✓ Exploratory analysis' END) || '
✓ Data export (CSV)
✓ Real-time Snowflake connection

**The app is live and ready to use!**';

    RETURN result;

EXCEPTION
    WHEN OTHER THEN
        result := '⚠️ Error creating Streamlit app: ' || :SQLCODE || ' - ' || :SQLERRM || '

**Troubleshooting:**
1. Verify you have CREATE STREAMLIT privilege on schema ANALYTICS
2. Check if app name ' || app_name || ' already exists
3. Verify warehouse HOOTSUITE_WH is available

**Manual deployment option:**
Run this SQL to see the generated code:
SELECT ''' || streamlit_code || '''';
        RETURN result;
END;
$$;

-- ============================================================================
-- Grant Permissions
-- ============================================================================
GRANT USAGE ON PROCEDURE HOOTSUITE_INTELLIGENCE.ANALYTICS.GENERATE_STREAMLIT_FROM_CHART(TEXT, TEXT, TEXT) TO ROLE SYSADMIN;
GRANT USAGE ON PROCEDURE HOOTSUITE_INTELLIGENCE.ANALYTICS.GENERATE_STREAMLIT_FROM_CHART(TEXT, TEXT, TEXT) TO ROLE PUBLIC;
GRANT CREATE STREAMLIT ON SCHEMA HOOTSUITE_INTELLIGENCE.ANALYTICS TO ROLE SYSADMIN;
GRANT CREATE STREAMLIT ON SCHEMA HOOTSUITE_INTELLIGENCE.ANALYTICS TO ROLE PUBLIC;

-- ============================================================================
-- Test Procedure (Commented out)
-- ============================================================================
-- CALL GENERATE_STREAMLIT_FROM_CHART(
--     'SELECT platform, COUNT(*) as post_count, AVG(follower_count) as avg_followers FROM HOOTSUITE_INTELLIGENCE.RAW.SOCIAL_ACCOUNTS GROUP BY platform',
--     'Platform Analysis Dashboard',
--     'exploratory'
-- );

SELECT 'Streamlit App Generator Procedure created successfully' AS STATUS;
